# Example render.yaml configuration
services:
  - type: web
    name: facebook-auction-management
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-connection-string
      - key: FACEBOOK_ACCESS_TOKEN
        value: 73f5b2c473b69a504559bbc510243d02
      - key: NODE_ENV
        value: production

